# DO NOT EDIT THIS FILE

import time
from pathlib import Path
from typing import Iterable, Optional

import numpy as np

from qvl.qlabs import QuanserInteractiveLabs
from qvl.system import QLabsSystem
from qvl.real_time import QLabsRealTime
from qvl.qcar2 import QLabsQCar2
from qvl.qdrone2 import QLabsQDrone2
from qvl.basic_shape import QLabsBasicShape
from qvl.free_camera import QLabsFreeCamera

from hal.products.mats_aica import SDCSRoadMap
from pal.resources import rtmodels_aica


# ----------------------------
# Configuration
# ----------------------------

QLABS_HOST = "localhost"
TITLE_STRING = "AICA Challenge 2026 - Time: 00:00 - Score: 0"
SPAWN_FILE = Path("spawn_locations.txt")

QCAR_ACTOR_ID = 0
QDRONE_ACTOR_ID = 1

QCAR_SCALE = [1.0, 1.0, 1.0]
QDRONE_SCALE = [2.0, 2.0, 2.0]
QDRONE_SPAWN_OFFSET = np.array([0.0, 0.0, 0.1])

ROADMAP_SCALE_FACTOR = 10.0
DEFAULT_GROUND_Z = 0.05

COLORS = {
    "pickup_marker": [0.0, 1.0, 0.0],
    "dropoff_marker": [1.0, 0.0, 0.0],
    "window_marker": [1.0, 1.0, 0.0],
    "crate": [120 / 255, 60 / 255, 30 / 255],
    "large_dropoff": [0.1, 0.1, 0.4],
}

PICKUP_NODE = 24

DROP_OFFS = [
    {
        "label": "Drop Location 1",
        "node": 2,
        "package_type": "Small",
        "window_offset": np.array([3.9, -7.2, 9.6]),
        "base_color": COLORS["dropoff_marker"],
        "floor": 4,
    },
    {
        "label": "Drop Location 2",
        "node": 14,
        "package_type": "Small",
        "window_offset": np.array([3.5, -12.9, 9.6]),
        "base_color": COLORS["dropoff_marker"],
        "floor": 3,
    },
    {
        "label": "Drop Location 3",
        "node": 20,
        "package_type": "Small",
        "window_offset": np.array([1.3, 2.0, 4.8]),
        "base_color": COLORS["dropoff_marker"],
        "floor": 2,
    },
    {
        "label": "Drop Location 4",
        "node": 22,
        "package_type": "Small",
        "window_offset": None,
        "base_color": COLORS["dropoff_marker"],
        "floor": 1,
    },
    {
        "label": "Drop Location 5",
        "node": 10,
        "package_type": "Large",
        "window_offset": None,
        "base_color": COLORS["large_dropoff"],
        "floor": 1,
    },
]


# ----------------------------
# Main workflow
# ----------------------------

def main() -> None:
    """Set up the QLabs environment, markers, and vehicle/drone actors."""
    qlabs = QuanserInteractiveLabs()

    print("Connecting to QLabs...")
    if not qlabs.open(QLABS_HOST):
        raise ConnectionError(f"Unable to connect to QLabs at '{QLABS_HOST}'.")

    print("Connected to QLabs.")

    try:
        initialize_environment(qlabs)

        place_camera(qlabs)

        roadmap = SDCSRoadMap(leftHandTraffic=False, useSmallMap=False)

        place_pickup(qlabs, roadmap)
        place_dropoffs(qlabs, roadmap)

        initial_positions = read_initial_positions(SPAWN_FILE)
        spawn_qcar(qlabs, initial_positions)
        spawn_qdrone(qlabs, initial_positions)

    finally:
        qlabs.close()
        print("QLabs connection closed.")

# ----------------------------
# Environment setup
# ----------------------------

def initialize_environment(qlabs: QuanserInteractiveLabs) -> None:
    """Prepare the QLabs environment for a fresh scenario run."""
    qlabs_system = QLabsSystem(qlabs)
    qlabs_system.set_title_string(TITLE_STRING)

    realtime = QLabsRealTime()
    realtime.terminate_all_real_time_models()

    basic_shape = QLabsBasicShape(qlabs)
    basic_shape.destroy_all_actors_of_class()

# ----------------------------
# Camera setup
# ----------------------------
def place_camera(qlabs: QuanserInteractiveLabs) -> None:
    camera = QLabsFreeCamera(qlabs)
    camera.destroy_all_actors_of_class()
    loc = [5, 15, 52]
    rot = [0, 90., 0.]
    camera.spawn_degrees(location=loc, rotation=rot)
    camera.possess()


# ----------------------------
# Scenario placement
# ----------------------------

def place_pickup(qlabs: QuanserInteractiveLabs, roadmap: SDCSRoadMap) -> None:
    """Place the pickup marker and pickup objects."""
    basic_shape = QLabsBasicShape(qlabs)
    pickup_location = get_node_location(roadmap, PICKUP_NODE)

    place_pickup_location(basic_shape, pickup_location)

    print("\n---- Pickup Location ----")
    print(f"Node: {PICKUP_NODE} (Python), {PICKUP_NODE + 1} (Matlab/Simulink)")
    print(f"Location: {pickup_location}")


def place_dropoffs(qlabs: QuanserInteractiveLabs, roadmap: SDCSRoadMap) -> None:
    """Place all configured dropoff locations."""
    for dropoff in DROP_OFFS:
        basic_shape = QLabsBasicShape(qlabs)

        node = dropoff["node"]
        location = get_node_location(roadmap, node)
        window_offset = dropoff["window_offset"]
        window_location = location + window_offset if window_offset is not None else None

        place_dropoff_location(
            basic_shape=basic_shape,
            common_location=location,
            specific_location=window_location,
            common_color=dropoff["base_color"],
        )

        print(f"\n---- {dropoff['label']} ----")
        print(f"Package Type: {dropoff['package_type']}")
        print(f"Node: {node} (Python), {node+1} (Matlab/Simulink)")
        print(f"Location: {location}")
        print(f"Floor: {dropoff['floor']}")
        print(f"Window Location: {window_location if window_location is not None else 'None'}")


# ----------------------------
# Actor spawning
# ----------------------------

def spawn_qcar(qlabs: QuanserInteractiveLabs, initial_positions: list[float]) -> None:
    """Spawn and start the QCar actor."""
    qcar_position = initial_positions[0:3]
    qcar_yaw_deg = initial_positions[3]

    qcar = QLabsQCar2(qlabs, True)
    qcar.destroy_all_actors_of_class()
    qcar.actorNumber = QCAR_ACTOR_ID
    qcar.destroy()

    qcar.spawn_id_degrees(
        actorNumber=QCAR_ACTOR_ID,
        location=qcar_position,
        rotation=[0, 0, qcar_yaw_deg],
        scale=QCAR_SCALE,
        configuration=0,
        waitForConfirmation=True,
    )

    realtime = QLabsRealTime()
    realtime.start_real_time_model(actorNumber=QCAR_ACTOR_ID, modelName=rtmodels_aica.QCAR2)
    time.sleep(1.0)


def spawn_qdrone(qlabs: QuanserInteractiveLabs, initial_positions: list[float]) -> None:
    """Spawn and start the QDrone actor."""
    qdrone_position = np.array(initial_positions[4:7]) + QDRONE_SPAWN_OFFSET
    qdrone_yaw_deg = initial_positions[7]

    qdrone = QLabsQDrone2(qlabs, True)
    qdrone.destroy_all_actors_of_class()
    qdrone.actorNumber = QDRONE_ACTOR_ID
    qdrone.destroy()

    qdrone.spawn_id_degrees(
        actorNumber=QDRONE_ACTOR_ID,
        location=qdrone_position,
        rotation=[0, 0, qdrone_yaw_deg],
        scale=QDRONE_SCALE,
        configuration=0,
        waitForConfirmation=True,
    )

    realtime = QLabsRealTime()
    realtime.start_real_time_model(actorNumber=QDRONE_ACTOR_ID, modelName=rtmodels_aica.QDRONE2_OPEN)
    time.sleep(1.0)


# ----------------------------
# Placement helpers
# ----------------------------

def place_pickup_location(basic_shape: QLabsBasicShape, location: np.ndarray) -> None:
    """Place the pickup marker and package shapes."""
    spawn_static_shape(
        basic_shape=basic_shape,
        location=location,
        rotation=[0, 0, 0],
        scale=[1.0, 1.0, 0.01],
        configuration=basic_shape.SHAPE_CYLINDER,
        color=COLORS["pickup_marker"],
    )

    spawn_static_shape(
        basic_shape=basic_shape,
        location=location + np.array([2.0, 1.0, 0.65]),
        rotation=[0, 0, 0],
        scale=[1.0, 1.0, 1.0],
        configuration=basic_shape.SHAPE_CUBE,
        color=COLORS["crate"],
    )

    spawn_static_shape(
        basic_shape=basic_shape,
        location=location + np.array([2.0, -1.0, 0.4]),
        rotation=[0, 0, 0],
        scale=[0.5, 0.5, 0.5],
        configuration=basic_shape.SHAPE_CUBE,
        color=COLORS["crate"],
    )


def place_dropoff_location(
    basic_shape: QLabsBasicShape,
    common_location: np.ndarray,
    specific_location: Optional[np.ndarray] = None,
    common_color: Optional[Iterable[float]] = None,
) -> None:
    """Place a common dropoff marker and, optionally, a specific window marker."""
    if common_color is None:
        common_color = COLORS["dropoff_marker"]

    spawn_static_shape(
        basic_shape=basic_shape,
        location=common_location + np.array([0.0, 0.0, 0.005]),
        rotation=[0, 0, 0],
        scale=[1.0, 1.0, 0.01],
        configuration=basic_shape.SHAPE_CYLINDER,
        color=common_color,
    )

    if specific_location is not None:
        spawn_static_shape(
            basic_shape=basic_shape,
            location=specific_location + np.array([0.0, 0.0, 0.01]),
            rotation=[0, 0, 0],
            scale=[1.0, 1.0, 0.02],
            configuration=basic_shape.SHAPE_CYLINDER,
            color=COLORS["window_marker"],
        )


def spawn_static_shape(
    basic_shape: QLabsBasicShape,
    location: Iterable[float],
    rotation: Iterable[float],
    scale: Iterable[float],
    configuration: int,
    color: Iterable[float],
) -> None:
    """Spawn a static basic shape with consistent material and physics settings."""
    basic_shape.spawn(
        location=location,
        rotation=rotation,
        scale=scale,
        configuration=configuration,
        waitForConfirmation=True,
    )
    basic_shape.set_material_properties(color=list(color))
    basic_shape.set_enable_collisions(False)
    basic_shape.set_enable_dynamics(False)


# ----------------------------
# Data helpers
# ----------------------------

def get_node_location(roadmap: SDCSRoadMap, node: int) -> np.ndarray:
    """Return the scaled world location for a roadmap node."""
    node_pose = ROADMAP_SCALE_FACTOR * roadmap.nodes[node].pose.flatten()
    return np.array([node_pose[0], node_pose[1], DEFAULT_GROUND_Z])


def read_initial_positions(filepath: Path) -> list[float]:
    """
    Read initial actor positions from a text file.

    Expected format:
        - one or more comma-separated float values per line
        - blank lines and lines starting with '#' are ignored

    Minimum required values:
        [qcar_x, qcar_y, qcar_z, qcar_yaw, qdrone_x, qdrone_y, qdrone_z, qdrone_yaw]
    """
    if not filepath.exists():
        raise FileNotFoundError(f"Spawn file not found: {filepath}")

    values: list[float] = []

    with filepath.open("r", encoding="utf-8") as file:
        for line_number, raw_line in enumerate(file, start=1):
            line = raw_line.strip()

            if not line or line.startswith("#"):
                continue

            try:
                parts = [float(value.strip()) for value in line.split(",")]
            except ValueError as exc:
                raise ValueError(
                    f"Invalid numeric value in {filepath} on line {line_number}: {raw_line.strip()}"
                ) from exc

            values.extend(parts)

    if len(values) < 8:
        raise ValueError(
            f"{filepath} must contain at least 8 numeric values, but found {len(values)}."
        )

    return values


if __name__ == "__main__":
    main()